In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
#importing dataset
df=pd.read_csv("house_price_prediction.csv")
display(df)

      Area  Bedrooms  Bathrooms  Floors  YearBuilt    Price
0     1360         5          4       3       1986   830739
1     4272         5          4       3       2018  1783490
2     3592         2          2       3       1982  1240886
3      966         4          2       2       1991   592593
4     4926         1          4       2       1986  1725758
...    ...       ...        ...     ...        ...      ...
1995  4994         5          4       3       2002  2023123
1996  3046         5          2       1       2019  1256903
1997  1062         5          1       2       2023   621350
1998  4062         3          1       2       2001  1415670
1999  2989         5          1       3       2003  1226475

[2000 rows x 6 columns]

In [3]:
df=df.drop_duplicates()

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.shape

(2000, 6)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Area       2000 non-null   int64
 1   Bedrooms   2000 non-null   int64
 2   Bathrooms  2000 non-null   int64
 3   Floors     2000 non-null   int64
 4   YearBuilt  2000 non-null   int64
 5   Price      2000 non-null   int64
dtypes: int64(6)
memory usage: 93.9 KB

In [7]:
df.describe()

,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Price
count,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2.000000e+03
mean,2786.209500,3.003500,2.55250,1.993500,2001.525000,1.126200e+06
std,1295.146799,1.424606,1.10899,0.809188,12.648532,4.062553e+05
min,501.000000,1.000000,1.00000,1.000000,1980.000000,2.135620e+05
25%,1653.000000,2.000000,2.00000,1.000000,1991.000000,7.830798e+05
50%,2833.000000,3.000000,3.00000,2.000000,2001.000000,1.141231e+06
75%,3887.500000,4.000000,4.00000,3.000000,2013.000000,1.459170e+06
max,4999.000000,5.000000,4.00000,3.000000,2023.000000,2.023123e+06

In [8]:
df.head()

   Area  Bedrooms  Bathrooms  Floors  YearBuilt    Price
0  1360         5          4       3       1986   830739
1  4272         5          4       3       2018  1783490
2  3592         2          2       3       1982  1240886
3   966         4          2       2       1991   592593
4  4926         1          4       2       1986  1725758

In [9]:
df.dropna(inplace = True)

In [10]:
df.isnull().sum()

Area         0
Bedrooms     0
Bathrooms    0
Floors       0
YearBuilt    0
Price        0
dtype: int64

In [11]:
X = df.drop('Price', axis=1)
y = df['Price']

In [12]:
print(X.isnull().sum())
print(y.isnull().sum())

Area         0
Bedrooms     0
Bathrooms    0
Floors       0
YearBuilt    0
dtype: int64
0

In [13]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train, y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42)

In [14]:

from sklearn.linear_model import Ridge 
model = Ridge(alpha=1.0)
model.fit(X_train , y_train)

Ridge()

In [15]:
#prediction
y_pred = model.predict(X_test)
y_pred

array([ 458117.09790166, 1296567.28744335,  913719.61707847,
        724242.27358334, 1184843.94316904, 1295164.41965223,
       1114440.50647406, 1256536.8954783 ,  925054.90377225,
       1494168.10256406, 1215318.07570553, 1197479.5819056 ,
       1485435.35936847, 1150206.99707733, 1410687.56804384,
        825902.26578751, 1679968.51009205, 1377916.6895494 ,
        777986.35008191,  559932.65053667, 1161209.6090121 ,
        904560.90019167, 1680801.34089019, 1674676.58619567,
        869937.38861159, 1762593.22409616,  609847.09924463,
        972312.55250815,  692541.61082058,  882279.46493186,
       1674416.16614505,  768496.03481571,  457402.32871086,
        999085.82174223, 1130249.04482138, 1614647.94818279,
        766249.68295291, 1819553.89154886, 1563336.92373838,
       1273311.11981208, 1434845.37027373,  845758.0221885 ,
       1062981.64870037, 1448573.18347946,  712858.73182332,
       1468792.93654297,  828630.89526681, 1318238.58856537,
       1768886.66280904, 1701713.23707577, 1649138.91073761,
       1449250.43348578, 1415906.5124144 , 1648919.83917087,
       1649585.67044816,  818196.81554802,  624352.54814537,
        666406.60249641, 1026540.2567233 , 1367326.84931827,
       1039695.55309995, 1401095.1574694 , 1512930.10607992,
        848960.15981601, 1378784.76211601,  449456.91557749,
       1300617.03151147, 1006291.64310099, 1399139.39333397,
       1093167.91959997,  458248.05134621, 1174729.54902155,
       1583456.17784811, 1691070.98774065, 1031365.490274  ,
        599189.94306346, 1009076.39912912, 1332000.71209385,
       1523731.11994654,  497803.02788447,  805859.54023575,
       1147005.31054676, 1752599.02637671, 1375778.28768287,
        483371.21623476,  619960.01451093,  722870.50491469,
        944247.87488527, 1306758.09829425,  674270.62194695,
       1319362.29531544, 1104031.37953071,  981268.21272268,
       1282750.95837491, 1712755.2812466 , 1421261.73043862,
       1124380.04755661,  956762.81991848, 1564903.55051981,
       1867203.47260715,  770684.2970722 , 1314583.85346581,
       1541167.07011522,  585640.80466336, 1559568.78887859,
       1164510.18198919, 1688665.56042224, 1005963.77589675,
       1677255.91243375, 1803721.56737123,  650243.55381498,
       1551817.96114947,  809335.16635928, 1135770.19572985,
        819754.19905918, 1600552.42265539,  446239.45963309,
       1780752.23117013, 1356196.68702525,  805242.17065298,
        463914.71675613, 1387145.93779473, 1250404.34714837,
       1828434.94663679, 1496706.06993848,  496380.54280483,
       1373545.25528091, 1398080.57605426,  803684.2444674 ,
       1223385.61189454, 1042453.45460889,  395002.16401719,
       1021247.79912175, 1208374.77997177, 1408921.9979898 ,
       1457145.01835361, 1212907.87803599, 1649004.00091434,
       1017034.05534373, 1548697.65933248, 1640019.18294722,
       1670969.28731523, 1378497.79370924,  675065.38612513,
        922915.95923129,  554620.06464098, 1132167.53844919,
       1136021.85903054, 1309706.62228196, 1075752.6314306 ,
        492345.91939458, 1345306.55892651,  487440.89748476,
       1657345.69050813, 1595754.57732906, 1464944.33944606,
        848046.76966845,  432377.73037547,  943146.65722733,
       1374938.8312064 , 1583082.18385155, 1459602.12098932,
        691734.79467342, 1767908.61392949, 1390666.53648381,
        514770.76920019,  408363.85050075,  912646.09856902,
       1686277.27851355,  759120.77237663,  645761.61428943,
       1006363.24186986,  472227.08572493,  604226.34604146,
       1222887.6619765 , 1430966.95847276, 1720959.41995188,
       1650659.50885097, 1472466.95187294, 1655864.31081901,
       1113034.09619756,  804986.21556421,  958407.98550568,
        695250.92840066, 1001167.08955825, 1119920.25788081,
       1803230.45694334,  579845.84060444,  814955.59724661,
        986612.8656164 ,  834974.27697789, 1390382.57685726,
       1036846.64934544,  965494.06730635, 1496323.34367726,
       1152968.2871685 ,  395056.60263408, 1213819.53586444,
       1808116.43590787,  741664.05966191,  695709.29795251,
        726466.44493954, 1135340.99766091, 1301197.23347193,
       1302636.30436031,  635657.97396221, 1605449.69055589,
       1280527.18718172,  572096.17186316,  939857.93137666,
       1443659.29810139, 1320198.83458918, 1232338.66825293,
       1335177.14045969, 1032414.39282792, 1278099.38723251,
       1342380.74915057, 1581168.80636403,  580362.52909043,
       1767726.40139954, 1519079.2402186 , 1257258.36499838,
       1705252.78814461, 1566288.52538422, 1404692.48479795,
        678596.9604036 ,  681327.49162666,  372792.97449651,
        740053.82968013, 1639922.34395211, 1278757.67690177,
       1728898.75803863, 1394738.99000266, 1146101.63746598,
       1485684.50562395, 1687284.52578375, 1139491.33880706,
       1711512.56771318, 1508607.88102294, 1618173.65404291,
        971100.84987023, 1400920.32234295,  593739.96572271,
       1584643.15602646,  904477.24048456,  971250.66653955,
       1022284.76951853,  663182.02437211, 1676666.34972975,
       1065869.23858449, 1108865.34534607,  682001.73285277,
       1466130.59280698,  612371.87836179, 1200844.10018899,
       1580911.05007823,  609675.03319079, 1442263.018785  ,
       1211665.76708566,  982768.45321408, 1387756.27677509,
        647284.67850859, 1425926.05090682, 1860632.57451548,
       1021102.56067936,  933549.69908282, 1678828.31706801,
       1123792.17177259, 1296233.16781055,  879898.5482612 ,
        574143.67998814, 1510207.66015126,  905498.66978339,
       1554613.65314089,  567751.61481343,  673608.18822115,
        652718.42714306, 1606769.78390724, 1585389.80110304,
       1228871.98344482, 1627532.28207788, 1446340.60217444,
        832270.30308023,  515431.49330644,  621799.87876746,
        610167.52437562, 1724226.94112882, 1529439.0177776 ,
       1198828.01584088, 1676357.00970412, 1590140.85472829,
        727839.91425849,  954292.49735671, 1621131.47566926,
       1728277.0230288 , 1508951.0066354 , 1229165.20904121,
        981883.65887408, 1146559.07081106, 1610244.75885232,
       1745260.97035124, 1198966.63413975,  689893.02071583,
        241283.63972425, 1377544.48301956,  467219.35219347,
        430543.08756702, 1373641.25619351, 1468727.59496371,
       1382615.22322807,  372511.03642556,  517550.40011878,
        925395.87662551,  784282.3237785 , 1274900.58724781,
        823083.4277525 , 1398295.38928742,  653203.796148  ,
       1272265.86824758,  608364.10050149,  865952.84837236,
        479550.8860828 ,  534891.40406686, 1244472.56598762,
        642344.68136726, 1172544.05583766, 1118012.55769938,
        727138.48246703,  893644.47475221, 1025924.27686672,
        646288.64512485,  590857.61897428, 1048375.96325303,
       1529558.67573941, 1594249.19799781, 1710940.1641492 ,
       1474658.32244442, 1220731.36718326,  591077.65365553,
       1135997.46343359, 1380495.57365979, 1207313.00250719,
       1028170.28371412, 1352650.29646625, 1124309.06034008,
        794225.39361613,  902698.44153521, 1216847.53728715,
       1392657.16258567, 1575198.02713762,  636876.71952232,
        733422.19514388,  747287.17046684, 1495750.39267779,
       1103328.43399302, 1211223.80119955, 1244991.59834506,
        667449.23646896, 1833561.20184179,  776966.30808679,
       1348852.41578032,  820972.5421177 ,  542025.11565113,
        842680.47473437, 1459142.5755231 , 1265027.50609428,
       1465272.83989025, 1910928.70477387,  579052.76435821,
        818938.85548992, 1428587.1181817 , 1051114.81284743,
        542007.11741664, 1300638.56504781, 1741619.84871008,
       1093543.30332272, 1702443.95883536,  670354.38900664,
        932846.45712508,  843198.53024699,  902441.76162901,
        951091.97878322, 1667394.56990261, 1837463.03894165,
        587327.22061019, 1273681.29105599, 1304082.44882773,
        652928.25543952,  725661.8721171 , 1462014.67626063,
       1485227.91456957, 1626473.46003711, 1286974.26531656,
        618985.71950611,  571210.82587949,  766551.6577405 ,
        490154.68002668, 1454735.44596672, 1473022.30956198,
       1412247.70689729])

In [16]:
X_test

      Area  Bedrooms  Bathrooms  Floors  YearBuilt
1860   633         1          4       2       2019
353   3856         1          1       2       2017
1333  1598         5          4       1       2013
905   1705         3          1       2       1990
1289  2564         5          2       3       2021
...    ...       ...        ...     ...        ...
965   1811         1          3       3       1987
1284   794         3          2       2       1987
1739  3540         4          4       2       1992
261   3670         5          2       2       2006
535   3519         5          1       3       2004

[400 rows x 5 columns]

In [17]:
y_test

1860     451698
353     1216780
1333     872531
905      742551
1289    1164428
         ...
965      845538
1284     607662
1739    1470114
261     1472689
535     1339238
Name: Price, Length: 400, dtype: int64

In [18]:

# slope & intercept 
m = model.coef_
c = model.intercept_
print("Slope(m):",m)
print("Intercept(c):",c)

#prediction Using Formula
x = 4
y_pred = m*x + c
print("m*4 + c =",y_pred)

Slope(m): [  300.26516805 50202.14193216 42438.29911955 28993.28655255
   994.77486113]
Intercept(c): -2018343.109608274
m*4 + c = [-2017142.04893608 -1817534.54187962 -1848589.91313007 -1902369.96339807
 -2014364.01016376]

In [19]:
y_pred=model.predict(X_test)
comparison = pd.DataFrame({"Actual Price":y_test, "Predicted Price":y_pred})
comparison.head()

      Actual Price  Predicted Price
1860        451698     4.581171e+05
353        1216780     1.296567e+06
1333        872531     9.137196e+05
905         742551     7.242423e+05
1289       1164428     1.184844e+06

In [20]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
print("R2 Score:",r2_score(y_test,y_pred))
print("MSE:",mean_squared_error(y_test,y_pred))
print("RMSE:",np.sqrt(mean_squared_error(y_test, y_pred)))
print("MAE:",mean_absolute_error(y_test, y_pred))

R2 Score: 0.9821782325513077
MSE: 2848920211.982293
RMSE: 53375.277160707024
MAE: 43628.48041310147

In [21]:
new_house=np.array([[2000, 5, 2, 4, 1997]])
predicted_price=model.predict(new_house)
print("Predicted House Prices:",predicted_price[0])

Predicted House Prices: 1020613.0782747432